# Generated by Django 5.1.6 on 2026-09-11 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0009_alter_associations_created_by"),
        ("members", "0011_rename_assosiation_coremember_association_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coremember",
            name="association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="committees.associations",
            ),
        ),
    ]
