# Generated by Django 5.1.6 on 2026-09-11 06:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0004_notification"),
        ("events", "0003_event_report_content_event_report_generated_and_more"),
        ("faculty", "0002_faculty_can_lock_dates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["date_time"]},
        ),
        migrations.AlterModelOptions(
            name="facultylockdate",
            options={"ordering": ["locked_date"]},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["location"]},
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="max_participants",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="event_posters/"),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="report_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="event",
            name="report_provider",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="event",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultylockdate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="faculty.faculty",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="location",
            field=models.CharField(default="online", max_length=255),
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Submitted for approval"),
                            ("updated", "Updated and resubmitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("calendar", "Added to Google Calendar"),
                            ("report", "Post-event report generated"),
                            ("report_edited", "Post-event report edited"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Login.userprofile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("attended", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to="Login.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["registered_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "participant"),
                        name="unique_event_registration",
                    )
                ],
            },
        ),
    ]
